# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

stages:
- stage: CI  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: CI  # friendly name to display in the UI 
  
  pool:
    vmImage: windows-2022

  variables:
    buildConfiguration: 'Release'
    backendProjectPath: 'diplomapp/backend/backend.csproj'
    frontendProjectPath: 'diplomapp/frontend/frontend.csproj'

  jobs: 
  - job: Builds
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mihsta'
        scannerMode: 'MSBuild'
        projectKey: 'mihsta_devops-diplom'
    
    - script: dotnet build $(backendProjectPath) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(backendProjectPath) $(buildConfiguration)'

    - script: dotnet build $(frontendProjectPath) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(frontendProjectPath) $(buildConfiguration)'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
#- stage: CD
#  jobs:
#  - job: B1
#  - job: B2