# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
parameters:
  - name: doPublish
    default: false
    type: boolean
    
trigger:
- main

stages:
- stage: CI_Build  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: CI_Build  # friendly name to display in the UI 
  
  pool:
    vmImage: windows-2022

  variables:
    buildConfiguration: 'Release'

  jobs: 
  - job: Build
    steps:

#SonarCloudPrepare
    - task: SonarCloudPrepare@1
      displayName: SonarCloud Prepare
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mihsta'
        scannerMode: 'MSBuild'
        projectKey: 'mihsta_devops-diplom'

#Build solution .NET CORE
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: 'build'
        projects: 
          diplomapp\diplomapp.sln        
        arguments: '--configuration $(buildConfiguration)'

# Run tests and auto publish test results.
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        workingDirectory: diplomapp
        arguments: '/p:CollectCoverage=true'

    - task: SonarCloudAnalyze@1
      displayName: SonarCloud Analyze
    - task: SonarCloudPublish@1
      displayName: SonarCloud Publish
      inputs:
        pollingTimeoutSec: '300'
    - task: sonarcloud-buildbreaker@2
      displayName: SonarCloud Breaker
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mihsta'


  - job: Publish
    dependsOn: Build    
    condition: and(succeeded(), eq('${{ parameters.doPublish }}', 'true'))
    steps:
# Publish projects to specified folder.    
    - task: DotNetCoreCLI@2
      displayName: dotnet publish backend --configuration $(buildConfiguration)
      name: PublishBackendProject
      inputs:
        command: publish
        projects: '**/backend/**/*.csproj'
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend_$(Build.BuildNumber)'
        zipAfterPublish: true

    - task: DotNetCoreCLI@2
      displayName: dotnet publish frontend --configuration $(buildConfiguration)
      name: PublishFrontendProject
      inputs:
        command: publish
        projects: '**/Frontend/**/*.csproj'
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/frontend_$(Build.BuildNumber)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend_$(Build.BuildNumber)'
        ArtifactName: 'Frontend_LatestBuild'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend_$(Build.BuildNumber)'
        ArtifactName: 'Backend_LatestBuild'
        publishLocation: 'Container'

  - job: Docker_buildAndPush
    steps:
      - checkout: self
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub'
          repository: 'mihailsta/diplomapp-frontend'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.frontend'
          tags: latest
          addPipelineData: false
          addBaseImageData: false


      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub'
          repository: 'mihailsta/diplomapp-backend'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.backend'
          tags: latest
          addPipelineData: false
          addBaseImageData: false

- stage: CI_Docker
  displayName: CI_Docker
  jobs:
    - job: buildAndPush
      steps:
      - checkout: self
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub'
          repository: 'mihailsta/diplomapp-frontend'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.frontend'
          tags: latest
          addPipelineData: false
          addBaseImageData: false


      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub'
          repository: 'mihailsta/diplomapp-backend'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.backend'
          tags: latest
          addPipelineData: false
          addBaseImageData: false
