# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-2022

variables:
  buildConfiguration: 'Release'
  backendProjectPath: 'diplomapp/backend/backend.csproj'


steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mihsta'
    scannerMode: 'MSBuild'
    projectKey: 'diplomapp'
    projectName: 'diplomapp'


- script: dotnet sonarscanner begin  /o:"mihsta" /k:"dipmlomapp"  /d:sonar.host.url="https://sonarcloud.io"
  displayName: dotnet sonarscanner begin

- script: dotnet build $(backendProjectPath) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(backendProjectPath) $(buildConfiguration)'

- script: dotnet sonarscanner end
  displayName: dotnet sonarscanner end

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
    