# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

trigger:
- main

stages:
- stage: CI  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: CI  # friendly name to display in the UI 
  
  pool:
    vmImage: windows-2022

  variables:
    buildConfiguration: 'Release'

  jobs: 
  - job: Builds
    steps:

#SonarCloudPrepare
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mihsta'
        scannerMode: 'MSBuild'
        projectKey: 'mihsta_devops-diplom'

#Build solution .NET CORE
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: 'build'
        projects: 
          diplomapp\diplomapp.sln        
        arguments: '--configuration $(buildConfiguration)'

# Run tests and auto publish test results.

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        workingDirectory: diplomapp
        arguments: '/p:CollectCoverage=true'

    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: sonarcloud-buildbreaker@2
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mihsta'

# Publish projects to specified folder.
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'    
        zipAfterPublish: true
        modifyOutputPath: true
  # - stage: CD
  #  jobs:
  #  - job: B1
  #  - job: B2
# - stage: QA
#  dependsOn: CI
#  jobs:
#  - job: Tests
#    steps: