FROM mcr.microsoft.com/dotnet/sdk:6.0 AS publish
WORKDIR /src
COPY ["diplomapp/frontend", "."]
RUN dotnet publish "frontend.csproj" -c Release -o /app/publish


FROM nginx:alpine AS final

EXPOSE 8080

WORKDIR /var/www/web
COPY --from=publish /app/publish/wwwroot .
COPY ["diplomapp/frontend/nginx.conf", "/etc/nginx/nginx.conf"]

# Healthcheck
# HEALTHCHECK --interval=15s --timeout=3s CMD curl -f http://localhost:80

RUN adduser -D appuser
USER appuser

