version: '3.1'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - 8080:80   
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend    
    restart: always
    ports:
      - 5030:80