FROM mcr.microsoft.com/dotnet/sdk:6.0 AS publish
WORKDIR /src
COPY ["diplomapp/frontend", "."]
RUN dotnet publish "frontend.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /var/www/web
COPY --from=publish /app/publish/wwwroot .
COPY ["diplomapp/frontend/nginx.conf", "/etc/nginx/nginx.conf"]
EXPOSE 8080