apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
      - image: {{ .Values.werf.image.frontend }}
        name: frontend
        ports:
        - containerPort: 8080
          name: frontend
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: "25m"
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: "frontend-service"
    port: 8080
  selector:
    app: frontend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica coun
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: 50 # target CPU utilization

---