apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
      - image: {{ .Values.werf.image.backend }}
        name: backend
        env:
        - name: CONNECTION_STRING
          value: {{ .Values.global.sql }}
        ports:
        - containerPort: 8080
          name: backend
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: "25m"
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: ClusterIP
  ports:
  - name: "backend-service"
    port: 8080    
  selector:
    app: backend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage: 50 # target CPU utilization