apiVersion: v1
kind: Secret
metadata:
  name: application-config
data:
  appsettings.json: dGVzdAo= 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: application-config    
      imagePullSecrets:
        - name: registrysecret
      containers:
      - image: {{ .Values.werf.image.backend }}
        name: backend
        ports:
        - containerPort: 8080
          name: backend
        volumeMounts:
          - name: application-config
            readOnly: true
            mountPath: /app/config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: ClusterIP
  ports:
  - name: "backend-service"
    port: 8080    
  selector:
    app: backend