#https://thomasthornton.cloud/2020/11/02/deploying-terraform-using-azure-devops-with-build-artifacts/

stages:
- stage: CI_TF
  displayName: CI_TF

  jobs:  
  - job: GetArtifacts
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Terraform files to artifacts'
      inputs:
        SourceFolder: iac/terraform
        TargetFolder: '$(build.artifactstagingdirectory)'
