trigger:
  branches:
    include:
    - main
  paths:
    include:
    - iac/terraform/*

stages:
- stage: CI_TF
  displayName: CI_TF

  jobs:  
  - job: GetArtifacts
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Terraform files to artifacts'
      inputs:
        SourceFolder: iac/terraform
        TargetFolder: '$(build.artifactstagingdirectory)/Terraform'
