#https://thomasthornton.cloud/2020/11/02/deploying-terraform-using-azure-devops-with-build-artifacts/

stages:
- stage: CI_TF
  displayName: CI_TF

  jobs:  

  - job: Terraforming
    steps:

    - task: TerraformInstaller@0
      displayName: 'Install Terraform latest'        
      inputs:
        terraformVersion: 'latest'
        
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'iac/terraform'
        backendServiceArm: 'ProductionSubscription(e7d25b87-6206-43f1-8056-f55fb43d9548)'
        backendAzureRmResourceGroupName: 'rg-terraformstate'
        backendAzureRmStorageAccountName: 'terrastatestorage5533'
        backendAzureRmContainerName: 'terraformstate'
        backendAzureRmKey: 'testimport.terraform.tfstate'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'iac/terraform'
        commandOptions: '--var "appId=$(TF_VAR_appId)" --var "password=$(TF_VAR_password)"'
        environmentServiceNameAzureRM: 'ProductionSubscription(e7d25b87-6206-43f1-8056-f55fb43d9548)'


