trigger:
  - main

paths:
  include:
   - iac/terraform/*

stages:
# Start CI
- stage: CIBuild  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: CI_Build  # friendly name to display in the UI 
  variables:
    buildConfiguration: 'Release'

# jobs CI
  jobs: 

 # Build
  - job: Build
    variables:
        NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

    pool:  
      vmImage: windows-2022 #https://docs.microsoft.com/ru-ru/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    steps:
    - checkout: self