version: '3.1'
services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile  
    restart: always
    ports:
      - 80:8080