name: Production Deployment
on:
  push:
    branches: [production]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    environment: prod-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_ENV_URL: "global.env_url=diplomapp.asis.org.ru"
          WERF_DIR: "diplomapp"
          #WERF_KUBE_CONTEXT: production
