name: Production DB migrations
on:
  push:
    branches: [production]    

jobs:
  production_db_migrations:
    name: production_db_migrations
    runs-on: ubuntu-latest
    environment: prod-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Run dotnet-ef db update migrations
        run: |
          dotnet tool install --global dotnet-ef          
          dotnet ef database update --project ./diplomapp/backend/backend.csproj
        env:
          CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}