name: Review Deployment Dismiss
on:
  pull_request:
    branches:      
      - '**'            # matches every branch
      - '!production'   # excludes production
    types:
      - closed

jobs:

  dismiss:
    name: Dismiss
    runs-on: ubuntu-latest
    environment: stage-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dismiss
        uses: werf/actions/dismiss@v1.2
        with:
          env: review-${{ github.event.number }}
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:          
          WERF_DIR: "diplomapp"