name: Staging Deployment
on:
  push:
    branches: [main]    

jobs:
  staging_db_migrations:
    name: staging_db_migrations
    runs-on: ubuntu-latest
    environment: stage-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - run: |
          dotnet build ./diplomapp/diplomapp.sln   