name: Staging Deployment
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    environment: stage-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: staging
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_ENV_URL: "global.env_url=diplomapp.stage.asis.org.ru"          
          WERF_SET_ENV_SQL: "global.sql=${{ secrets.SQL_CONNECTION_STRING }}"
          WERF_DIR: "diplomapp"      